version: '2'
networks:
  net1:

services:
  nginx:
    image: nginx:1
    ports:
     - 80:80
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/lizmap:/srv/lizmap
    networks:
      net1:
        aliases:
          - nginx
  lizmap:
    image: 3liz/lizmap-web-client:3.3
    command:
      - php-fpm
    environment:
      LIZMAP_WPS_URL: http://wps:8080/
      LIZMAP_DEBUGMODE: DEBUG
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_USER: '1000'
      LIZMAP_WMSSERVERURL: http://qgiserver:8080/ows/
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_HOME: /srv/lizmap
    expose:
      - 9000
    volumes:
      - ./volumes/projects:/srv/projects
      - ./volumes/lizmap/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ./volumes/lizmap/var/lizmap-config:/www/lizmap/var/config
      - ./volumes/lizmap/var/lizmap-db:/www/lizmap/var/db
      - ./volumes/lizmap/www:/www/lizmap/www
      - ./volumes/lizmap/var/log/lizmap:/www/lizmap/var/log
    restart: unless-stopped
    entrypoint: >
      sh -c " chown -R $${LIZMAP_USER} /tmp && /bin/lizmap-entrypoint.sh php-fpm"
    networks:
      net1:
        aliases:
          - lizmap
  qgiserver:
    image: 3liz/qgis-map-server:3.4
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_SERVER_WORKERS: 4
      QGSRV_CACHE_SIZE: '20'
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_USER: 1000:1000
      ROUTER_HOST: map
      QGSRV_ZMQ_IDENTITY: OWS-SERVER
      QGSRV_ZMQ_INADDR: tcp://*:18080
      QGSRV_ZMQ_MAXQUEUE: 1000
      QGSRV_ZMQ_TIMEOUT: 15000
      LIBGL_DEBUG: verbose glxinfo
    volumes:
      - ./volumes/projects:/srv/projects
    restart: unless-stopped
    ports:
     - 8080:8080
    expose:
      - 8080
      - 18080
    networks:
      net1:
        aliases:
          - qgiserver
  redis:
    image: redis:4
    restart: always
#    volumes:
 #     - ./lizmap/redis4:/data
    expose:
      - 6379
    networks:
      net1:
        aliases:
          - redis
